export const DAILY_GOAL_MODULE_TOKENS = {
    DAILY_GOAL_QUEUE: "DAILY_GOAL_QUEUE",
    DAILY_GOAL_REPOSITORY: "DAILY_GOAL_REPOSITORY",
    CLOCK: "CLOCK",
    GET_OR_CREATE_TODAY_GOAL_USE_CASE: "GET_OR_CREATE_TODAY_GOAL_USE_CASE",
    MARK_ITEM_COMPLETE_USE_CASE: "MARK_ITEM_COMPLETE_USE_CASE",
    ENSURE_TODAY_GOALS_FOR_ALL_USERS_USE_CASE: "ENSURE_TODAY_GOALS_FOR_ALL_USERS_USE_CASE",
} as const;
